# EMBEDDED SERVER CONFIGURATION
server:
  contextPath: /api

app:
  name: demo

jwt:
  header: Authorization
  expires_in: 600 # 10 minutes
  mobile_expires_in: 600 # 10 minutes
  secret: medicsi786%
  cookie: AUTH-TOKEN
